# Example of how to definite a cirq circuit
# main code should import cirq
def build_circuit():
    '''Function that builds the cirq circuit'''
    import numpy as np
    from cirq.ops import CNOT, CCNOT

    # initialise qubits
    qubits = [cirq.GridQubit(i, 0) for i in range(129)]

    # initialise moments (veritcal slices)
    moments = []

    # add vertical slices
    moments.append([CNOT(qubits[64], qubits[0])])
    moments.append([CNOT(qubits[2], qubits[66])])
    moments.append([CNOT(qubits[3], qubits[67])])
    moments.append([CNOT(qubits[4], qubits[68])])
    moments.append([CNOT(qubits[5], qubits[69])])
    moments.append([CNOT(qubits[6], qubits[70])])
    moments.append([CNOT(qubits[7], qubits[71])])
    moments.append([CNOT(qubits[8], qubits[72])])
    moments.append([CNOT(qubits[9], qubits[73])])
    moments.append([CNOT(qubits[10], qubits[74])])
    moments.append([CNOT(qubits[11], qubits[75])])
    moments.append([CNOT(qubits[12], qubits[76])])
    moments.append([CNOT(qubits[13], qubits[77])])
    moments.append([CNOT(qubits[14], qubits[78])])
    moments.append([CNOT(qubits[15], qubits[79])])
    moments.append([CNOT(qubits[16], qubits[80])])
    moments.append([CNOT(qubits[17], qubits[81])])
    moments.append([CNOT(qubits[18], qubits[82])])
    moments.append([CNOT(qubits[19], qubits[83])])
    moments.append([CNOT(qubits[20], qubits[84])])
    moments.append([CNOT(qubits[21], qubits[85])])
    moments.append([CNOT(qubits[22], qubits[86])])
    moments.append([CNOT(qubits[23], qubits[87])])
    moments.append([CNOT(qubits[24], qubits[88])])
    moments.append([CNOT(qubits[25], qubits[89])])
    moments.append([CNOT(qubits[26], qubits[90])])
    moments.append([CNOT(qubits[27], qubits[91])])
    moments.append([CNOT(qubits[28], qubits[92])])
    moments.append([CNOT(qubits[29], qubits[93])])
    moments.append([CNOT(qubits[30], qubits[94])])
    moments.append([CNOT(qubits[31], qubits[95])])
    moments.append([CNOT(qubits[32], qubits[96])])
    moments.append([CNOT(qubits[33], qubits[97])])
    moments.append([CNOT(qubits[34], qubits[98])])
    moments.append([CNOT(qubits[35], qubits[99])])
    moments.append([CNOT(qubits[36], qubits[100])])
    moments.append([CNOT(qubits[37], qubits[101])])
    moments.append([CNOT(qubits[38], qubits[102])])
    moments.append([CNOT(qubits[39], qubits[103])])
    moments.append([CNOT(qubits[40], qubits[104])])
    moments.append([CNOT(qubits[41], qubits[105])])
    moments.append([CNOT(qubits[42], qubits[106])])
    moments.append([CNOT(qubits[43], qubits[107])])
    moments.append([CNOT(qubits[44], qubits[108])])
    moments.append([CNOT(qubits[45], qubits[109])])
    moments.append([CNOT(qubits[46], qubits[110])])
    moments.append([CNOT(qubits[47], qubits[111])])
    moments.append([CNOT(qubits[48], qubits[112])])
    moments.append([CNOT(qubits[49], qubits[113])])
    moments.append([CNOT(qubits[50], qubits[114])])
    moments.append([CNOT(qubits[51], qubits[115])])
    moments.append([CNOT(qubits[52], qubits[116])])
    moments.append([CNOT(qubits[53], qubits[117])])
    moments.append([CNOT(qubits[54], qubits[118])])
    moments.append([CNOT(qubits[55], qubits[119])])
    moments.append([CNOT(qubits[56], qubits[120])])
    moments.append([CNOT(qubits[57], qubits[121])])
    moments.append([CNOT(qubits[58], qubits[122])])
    moments.append([CNOT(qubits[59], qubits[123])])
    moments.append([CNOT(qubits[60], qubits[124])])
    moments.append([CNOT(qubits[61], qubits[125])])
    moments.append([CNOT(qubits[62], qubits[126])])
    moments.append([CNOT(qubits[63], qubits[127])])
    moments.append([CNOT(qubits[64], qubits[128])])
    moments.append([CNOT(qubits[63], qubits[64]), CNOT(qubits[62], qubits[63]), CNOT(qubits[61], qubits[62]), CNOT(qubits[60], qubits[61]), CNOT(qubits[59], qubits[60]), CNOT(qubits[58], qubits[59]), CNOT(qubits[57], qubits[58]), CNOT(qubits[56], qubits[57]), CNOT(qubits[55], qubits[56]), CNOT(qubits[54], qubits[55]), CNOT(qubits[53], qubits[54]), CNOT(qubits[52], qubits[53]), CNOT(qubits[51], qubits[52]), CNOT(qubits[50], qubits[51]), CNOT(qubits[49], qubits[50]), CNOT(qubits[48], qubits[49]), CNOT(qubits[47], qubits[48]), CNOT(qubits[46], qubits[47]), CNOT(qubits[45], qubits[46]), CNOT(qubits[44], qubits[45]), CNOT(qubits[43], qubits[44]), CNOT(qubits[42], qubits[43]), CNOT(qubits[41], qubits[42]), CNOT(qubits[40], qubits[41]), CNOT(qubits[39], qubits[40]), CNOT(qubits[38], qubits[39]), CNOT(qubits[37], qubits[38]), CNOT(qubits[36], qubits[37]), CNOT(qubits[35], qubits[36]), CNOT(qubits[34], qubits[35]), CNOT(qubits[33], qubits[34]), CNOT(qubits[32], qubits[33]), CNOT(qubits[31], qubits[32]), CNOT(qubits[30], qubits[31]), CNOT(qubits[29], qubits[30]), CNOT(qubits[28], qubits[29]), CNOT(qubits[27], qubits[28]), CNOT(qubits[26], qubits[27]), CNOT(qubits[25], qubits[26]), CNOT(qubits[24], qubits[25]), CNOT(qubits[23], qubits[24]), CNOT(qubits[22], qubits[23]), CNOT(qubits[21], qubits[22]), CNOT(qubits[20], qubits[21]), CNOT(qubits[19], qubits[20]), CNOT(qubits[18], qubits[19]), CNOT(qubits[17], qubits[18]), CNOT(qubits[16], qubits[17]), CNOT(qubits[15], qubits[16]), CNOT(qubits[14], qubits[15]), CNOT(qubits[13], qubits[14]), CNOT(qubits[12], qubits[13]), CNOT(qubits[11], qubits[12]), CNOT(qubits[10], qubits[11]), CNOT(qubits[9], qubits[10]), CNOT(qubits[8], qubits[9]), CNOT(qubits[7], qubits[8]), CNOT(qubits[6], qubits[7]), CNOT(qubits[5], qubits[6]), CNOT(qubits[4], qubits[5]), CNOT(qubits[3], qubits[4]), CNOT(qubits[2], qubits[3])])
    moments.append([CCNOT(qubits[1], qubits[65], qubits[2])])
    moments.append([CCNOT(qubits[2], qubits[66], qubits[3])])
    moments.append([CCNOT(qubits[3], qubits[67], qubits[4])])
    moments.append([CCNOT(qubits[4], qubits[68], qubits[5])])
    moments.append([CCNOT(qubits[5], qubits[69], qubits[6])])
    moments.append([CCNOT(qubits[6], qubits[70], qubits[7])])
    moments.append([CCNOT(qubits[7], qubits[71], qubits[8])])
    moments.append([CCNOT(qubits[8], qubits[72], qubits[9])])
    moments.append([CCNOT(qubits[9], qubits[73], qubits[10])])
    moments.append([CCNOT(qubits[10], qubits[74], qubits[11])])
    moments.append([CCNOT(qubits[11], qubits[75], qubits[12])])
    moments.append([CCNOT(qubits[12], qubits[76], qubits[13])])
    moments.append([CCNOT(qubits[13], qubits[77], qubits[14])])
    moments.append([CCNOT(qubits[14], qubits[78], qubits[15])])
    moments.append([CCNOT(qubits[15], qubits[79], qubits[16])])
    moments.append([CCNOT(qubits[16], qubits[80], qubits[17])])
    moments.append([CCNOT(qubits[17], qubits[81], qubits[18])])
    moments.append([CCNOT(qubits[18], qubits[82], qubits[19])])
    moments.append([CCNOT(qubits[19], qubits[83], qubits[20])])
    moments.append([CCNOT(qubits[20], qubits[84], qubits[21])])
    moments.append([CCNOT(qubits[21], qubits[85], qubits[22])])
    moments.append([CCNOT(qubits[22], qubits[86], qubits[23])])
    moments.append([CCNOT(qubits[23], qubits[87], qubits[24])])
    moments.append([CCNOT(qubits[24], qubits[88], qubits[25])])
    moments.append([CCNOT(qubits[25], qubits[89], qubits[26])])
    moments.append([CCNOT(qubits[26], qubits[90], qubits[27])])
    moments.append([CCNOT(qubits[27], qubits[91], qubits[28])])
    moments.append([CCNOT(qubits[28], qubits[92], qubits[29])])
    moments.append([CCNOT(qubits[29], qubits[93], qubits[30])])
    moments.append([CCNOT(qubits[30], qubits[94], qubits[31])])
    moments.append([CCNOT(qubits[31], qubits[95], qubits[32])])
    moments.append([CCNOT(qubits[32], qubits[96], qubits[33])])
    moments.append([CCNOT(qubits[33], qubits[97], qubits[34])])
    moments.append([CCNOT(qubits[34], qubits[98], qubits[35])])
    moments.append([CCNOT(qubits[35], qubits[99], qubits[36])])
    moments.append([CCNOT(qubits[36], qubits[100], qubits[37])])
    moments.append([CCNOT(qubits[37], qubits[101], qubits[38])])
    moments.append([CCNOT(qubits[38], qubits[102], qubits[39])])
    moments.append([CCNOT(qubits[39], qubits[103], qubits[40])])
    moments.append([CCNOT(qubits[40], qubits[104], qubits[41])])
    moments.append([CCNOT(qubits[41], qubits[105], qubits[42])])
    moments.append([CCNOT(qubits[42], qubits[106], qubits[43])])
    moments.append([CCNOT(qubits[43], qubits[107], qubits[44])])
    moments.append([CCNOT(qubits[44], qubits[108], qubits[45])])
    moments.append([CCNOT(qubits[45], qubits[109], qubits[46])])
    moments.append([CCNOT(qubits[46], qubits[110], qubits[47])])
    moments.append([CCNOT(qubits[47], qubits[111], qubits[48])])
    moments.append([CCNOT(qubits[48], qubits[112], qubits[49])])
    moments.append([CCNOT(qubits[49], qubits[113], qubits[50])])
    moments.append([CCNOT(qubits[50], qubits[114], qubits[51])])
    moments.append([CCNOT(qubits[51], qubits[115], qubits[52])])
    moments.append([CCNOT(qubits[52], qubits[116], qubits[53])])
    moments.append([CCNOT(qubits[53], qubits[117], qubits[54])])
    moments.append([CCNOT(qubits[54], qubits[118], qubits[55])])
    moments.append([CCNOT(qubits[55], qubits[119], qubits[56])])
    moments.append([CCNOT(qubits[56], qubits[120], qubits[57])])
    moments.append([CCNOT(qubits[57], qubits[121], qubits[58])])
    moments.append([CCNOT(qubits[58], qubits[122], qubits[59])])
    moments.append([CCNOT(qubits[59], qubits[123], qubits[60])])
    moments.append([CCNOT(qubits[60], qubits[124], qubits[61])])
    moments.append([CCNOT(qubits[61], qubits[125], qubits[62])])
    moments.append([CCNOT(qubits[62], qubits[126], qubits[63])])
    moments.append([CCNOT(qubits[63], qubits[127], qubits[64])])
    moments.append([CCNOT(qubits[64], qubits[128], qubits[0])])
    moments.append([CNOT(qubits[64], qubits[128])])
    moments.append([CCNOT(qubits[63], qubits[127], qubits[64])])
    moments.append([CNOT(qubits[63], qubits[127])])
    moments.append([CCNOT(qubits[62], qubits[126], qubits[63])])
    moments.append([CNOT(qubits[62], qubits[126])])
    moments.append([CCNOT(qubits[61], qubits[125], qubits[62])])
    moments.append([CNOT(qubits[61], qubits[125])])
    moments.append([CCNOT(qubits[60], qubits[124], qubits[61])])
    moments.append([CNOT(qubits[60], qubits[124])])
    moments.append([CCNOT(qubits[59], qubits[123], qubits[60])])
    moments.append([CNOT(qubits[59], qubits[123])])
    moments.append([CCNOT(qubits[58], qubits[122], qubits[59])])
    moments.append([CNOT(qubits[58], qubits[122])])
    moments.append([CCNOT(qubits[57], qubits[121], qubits[58])])
    moments.append([CNOT(qubits[57], qubits[121])])
    moments.append([CCNOT(qubits[56], qubits[120], qubits[57])])
    moments.append([CNOT(qubits[56], qubits[120])])
    moments.append([CCNOT(qubits[55], qubits[119], qubits[56])])
    moments.append([CNOT(qubits[55], qubits[119])])
    moments.append([CCNOT(qubits[54], qubits[118], qubits[55])])
    moments.append([CNOT(qubits[54], qubits[118])])
    moments.append([CCNOT(qubits[53], qubits[117], qubits[54])])
    moments.append([CNOT(qubits[53], qubits[117])])
    moments.append([CCNOT(qubits[52], qubits[116], qubits[53])])
    moments.append([CNOT(qubits[52], qubits[116])])
    moments.append([CCNOT(qubits[51], qubits[115], qubits[52])])
    moments.append([CNOT(qubits[51], qubits[115])])
    moments.append([CCNOT(qubits[50], qubits[114], qubits[51])])
    moments.append([CNOT(qubits[50], qubits[114])])
    moments.append([CCNOT(qubits[49], qubits[113], qubits[50])])
    moments.append([CNOT(qubits[49], qubits[113])])
    moments.append([CCNOT(qubits[48], qubits[112], qubits[49])])
    moments.append([CNOT(qubits[48], qubits[112])])
    moments.append([CCNOT(qubits[47], qubits[111], qubits[48])])
    moments.append([CNOT(qubits[47], qubits[111])])
    moments.append([CCNOT(qubits[46], qubits[110], qubits[47])])
    moments.append([CNOT(qubits[46], qubits[110])])
    moments.append([CCNOT(qubits[45], qubits[109], qubits[46])])
    moments.append([CNOT(qubits[45], qubits[109])])
    moments.append([CCNOT(qubits[44], qubits[108], qubits[45])])
    moments.append([CNOT(qubits[44], qubits[108])])
    moments.append([CCNOT(qubits[43], qubits[107], qubits[44])])
    moments.append([CNOT(qubits[43], qubits[107])])
    moments.append([CCNOT(qubits[42], qubits[106], qubits[43])])
    moments.append([CNOT(qubits[42], qubits[106])])
    moments.append([CCNOT(qubits[41], qubits[105], qubits[42])])
    moments.append([CNOT(qubits[41], qubits[105])])
    moments.append([CCNOT(qubits[40], qubits[104], qubits[41])])
    moments.append([CNOT(qubits[40], qubits[104])])
    moments.append([CCNOT(qubits[39], qubits[103], qubits[40])])
    moments.append([CNOT(qubits[39], qubits[103])])
    moments.append([CCNOT(qubits[38], qubits[102], qubits[39])])
    moments.append([CNOT(qubits[38], qubits[102])])
    moments.append([CCNOT(qubits[37], qubits[101], qubits[38])])
    moments.append([CNOT(qubits[37], qubits[101])])
    moments.append([CCNOT(qubits[36], qubits[100], qubits[37])])
    moments.append([CNOT(qubits[36], qubits[100])])
    moments.append([CCNOT(qubits[35], qubits[99], qubits[36])])
    moments.append([CNOT(qubits[35], qubits[99])])
    moments.append([CCNOT(qubits[34], qubits[98], qubits[35])])
    moments.append([CNOT(qubits[34], qubits[98])])
    moments.append([CCNOT(qubits[33], qubits[97], qubits[34])])
    moments.append([CNOT(qubits[33], qubits[97])])
    moments.append([CCNOT(qubits[32], qubits[96], qubits[33])])
    moments.append([CNOT(qubits[32], qubits[96])])
    moments.append([CCNOT(qubits[31], qubits[95], qubits[32])])
    moments.append([CNOT(qubits[31], qubits[95])])
    moments.append([CCNOT(qubits[30], qubits[94], qubits[31])])
    moments.append([CNOT(qubits[30], qubits[94])])
    moments.append([CCNOT(qubits[29], qubits[93], qubits[30])])
    moments.append([CNOT(qubits[29], qubits[93])])
    moments.append([CCNOT(qubits[28], qubits[92], qubits[29])])
    moments.append([CNOT(qubits[28], qubits[92])])
    moments.append([CCNOT(qubits[27], qubits[91], qubits[28])])
    moments.append([CNOT(qubits[27], qubits[91])])
    moments.append([CCNOT(qubits[26], qubits[90], qubits[27])])
    moments.append([CNOT(qubits[26], qubits[90])])
    moments.append([CCNOT(qubits[25], qubits[89], qubits[26])])
    moments.append([CNOT(qubits[25], qubits[89])])
    moments.append([CCNOT(qubits[24], qubits[88], qubits[25])])
    moments.append([CNOT(qubits[24], qubits[88])])
    moments.append([CCNOT(qubits[23], qubits[87], qubits[24])])
    moments.append([CNOT(qubits[23], qubits[87])])
    moments.append([CCNOT(qubits[22], qubits[86], qubits[23])])
    moments.append([CNOT(qubits[22], qubits[86])])
    moments.append([CCNOT(qubits[21], qubits[85], qubits[22])])
    moments.append([CNOT(qubits[21], qubits[85])])
    moments.append([CCNOT(qubits[20], qubits[84], qubits[21])])
    moments.append([CNOT(qubits[20], qubits[84])])
    moments.append([CCNOT(qubits[19], qubits[83], qubits[20])])
    moments.append([CNOT(qubits[19], qubits[83])])
    moments.append([CCNOT(qubits[18], qubits[82], qubits[19])])
    moments.append([CNOT(qubits[18], qubits[82])])
    moments.append([CCNOT(qubits[17], qubits[81], qubits[18])])
    moments.append([CNOT(qubits[17], qubits[81])])
    moments.append([CCNOT(qubits[16], qubits[80], qubits[17])])
    moments.append([CNOT(qubits[16], qubits[80])])
    moments.append([CCNOT(qubits[15], qubits[79], qubits[16])])
    moments.append([CNOT(qubits[15], qubits[79])])
    moments.append([CCNOT(qubits[14], qubits[78], qubits[15])])
    moments.append([CNOT(qubits[14], qubits[78])])
    moments.append([CCNOT(qubits[13], qubits[77], qubits[14])])
    moments.append([CNOT(qubits[13], qubits[77])])
    moments.append([CCNOT(qubits[12], qubits[76], qubits[13])])
    moments.append([CNOT(qubits[12], qubits[76])])
    moments.append([CCNOT(qubits[11], qubits[75], qubits[12])])
    moments.append([CNOT(qubits[11], qubits[75])])
    moments.append([CCNOT(qubits[10], qubits[74], qubits[11])])
    moments.append([CNOT(qubits[10], qubits[74])])
    moments.append([CCNOT(qubits[9], qubits[73], qubits[10])])
    moments.append([CNOT(qubits[9], qubits[73])])
    moments.append([CCNOT(qubits[8], qubits[72], qubits[9])])
    moments.append([CNOT(qubits[8], qubits[72])])
    moments.append([CCNOT(qubits[7], qubits[71], qubits[8])])
    moments.append([CNOT(qubits[7], qubits[71])])
    moments.append([CCNOT(qubits[6], qubits[70], qubits[7])])
    moments.append([CNOT(qubits[6], qubits[70])])
    moments.append([CCNOT(qubits[5], qubits[69], qubits[6])])
    moments.append([CNOT(qubits[5], qubits[69])])
    moments.append([CCNOT(qubits[4], qubits[68], qubits[5])])
    moments.append([CNOT(qubits[4], qubits[68])])
    moments.append([CCNOT(qubits[3], qubits[67], qubits[4])])
    moments.append([CNOT(qubits[3], qubits[67])])
    moments.append([CCNOT(qubits[2], qubits[66], qubits[3])])
    moments.append([CNOT(qubits[2], qubits[66])])
    moments.append([CCNOT(qubits[1], qubits[65], qubits[2])])
    moments.append([CNOT(qubits[2], qubits[3]), CNOT(qubits[3], qubits[4]), CNOT(qubits[4], qubits[5]), CNOT(qubits[5], qubits[6]), CNOT(qubits[6], qubits[7]), CNOT(qubits[7], qubits[8]), CNOT(qubits[8], qubits[9]), CNOT(qubits[9], qubits[10]), CNOT(qubits[10], qubits[11]), CNOT(qubits[11], qubits[12]), CNOT(qubits[12], qubits[13]), CNOT(qubits[13], qubits[14]), CNOT(qubits[14], qubits[15]), CNOT(qubits[15], qubits[16]), CNOT(qubits[16], qubits[17]), CNOT(qubits[17], qubits[18]), CNOT(qubits[18], qubits[19]), CNOT(qubits[19], qubits[20]), CNOT(qubits[20], qubits[21]), CNOT(qubits[21], qubits[22]), CNOT(qubits[22], qubits[23]), CNOT(qubits[23], qubits[24]), CNOT(qubits[24], qubits[25]), CNOT(qubits[25], qubits[26]), CNOT(qubits[26], qubits[27]), CNOT(qubits[27], qubits[28]), CNOT(qubits[28], qubits[29]), CNOT(qubits[29], qubits[30]), CNOT(qubits[30], qubits[31]), CNOT(qubits[31], qubits[32]), CNOT(qubits[32], qubits[33]), CNOT(qubits[33], qubits[34]), CNOT(qubits[34], qubits[35]), CNOT(qubits[35], qubits[36]), CNOT(qubits[36], qubits[37]), CNOT(qubits[37], qubits[38]), CNOT(qubits[38], qubits[39]), CNOT(qubits[39], qubits[40]), CNOT(qubits[40], qubits[41]), CNOT(qubits[41], qubits[42]), CNOT(qubits[42], qubits[43]), CNOT(qubits[43], qubits[44]), CNOT(qubits[44], qubits[45]), CNOT(qubits[45], qubits[46]), CNOT(qubits[46], qubits[47]), CNOT(qubits[47], qubits[48]), CNOT(qubits[48], qubits[49]), CNOT(qubits[49], qubits[50]), CNOT(qubits[50], qubits[51]), CNOT(qubits[51], qubits[52]), CNOT(qubits[52], qubits[53]), CNOT(qubits[53], qubits[54]), CNOT(qubits[54], qubits[55]), CNOT(qubits[55], qubits[56]), CNOT(qubits[56], qubits[57]), CNOT(qubits[57], qubits[58]), CNOT(qubits[58], qubits[59]), CNOT(qubits[59], qubits[60]), CNOT(qubits[60], qubits[61]), CNOT(qubits[61], qubits[62]), CNOT(qubits[62], qubits[63]), CNOT(qubits[63], qubits[64])])
    moments.append([CNOT(qubits[64], qubits[128])])
    moments.append([CNOT(qubits[63], qubits[127])])
    moments.append([CNOT(qubits[62], qubits[126])])
    moments.append([CNOT(qubits[61], qubits[125])])
    moments.append([CNOT(qubits[60], qubits[124])])
    moments.append([CNOT(qubits[59], qubits[123])])
    moments.append([CNOT(qubits[58], qubits[122])])
    moments.append([CNOT(qubits[57], qubits[121])])
    moments.append([CNOT(qubits[56], qubits[120])])
    moments.append([CNOT(qubits[55], qubits[119])])
    moments.append([CNOT(qubits[54], qubits[118])])
    moments.append([CNOT(qubits[53], qubits[117])])
    moments.append([CNOT(qubits[52], qubits[116])])
    moments.append([CNOT(qubits[51], qubits[115])])
    moments.append([CNOT(qubits[50], qubits[114])])
    moments.append([CNOT(qubits[49], qubits[113])])
    moments.append([CNOT(qubits[48], qubits[112])])
    moments.append([CNOT(qubits[47], qubits[111])])
    moments.append([CNOT(qubits[46], qubits[110])])
    moments.append([CNOT(qubits[45], qubits[109])])
    moments.append([CNOT(qubits[44], qubits[108])])
    moments.append([CNOT(qubits[43], qubits[107])])
    moments.append([CNOT(qubits[42], qubits[106])])
    moments.append([CNOT(qubits[41], qubits[105])])
    moments.append([CNOT(qubits[40], qubits[104])])
    moments.append([CNOT(qubits[39], qubits[103])])
    moments.append([CNOT(qubits[38], qubits[102])])
    moments.append([CNOT(qubits[37], qubits[101])])
    moments.append([CNOT(qubits[36], qubits[100])])
    moments.append([CNOT(qubits[35], qubits[99])])
    moments.append([CNOT(qubits[34], qubits[98])])
    moments.append([CNOT(qubits[33], qubits[97])])
    moments.append([CNOT(qubits[32], qubits[96])])
    moments.append([CNOT(qubits[31], qubits[95])])
    moments.append([CNOT(qubits[30], qubits[94])])
    moments.append([CNOT(qubits[29], qubits[93])])
    moments.append([CNOT(qubits[28], qubits[92])])
    moments.append([CNOT(qubits[27], qubits[91])])
    moments.append([CNOT(qubits[26], qubits[90])])
    moments.append([CNOT(qubits[25], qubits[89])])
    moments.append([CNOT(qubits[24], qubits[88])])
    moments.append([CNOT(qubits[23], qubits[87])])
    moments.append([CNOT(qubits[22], qubits[86])])
    moments.append([CNOT(qubits[21], qubits[85])])
    moments.append([CNOT(qubits[20], qubits[84])])
    moments.append([CNOT(qubits[19], qubits[83])])
    moments.append([CNOT(qubits[18], qubits[82])])
    moments.append([CNOT(qubits[17], qubits[81])])
    moments.append([CNOT(qubits[16], qubits[80])])
    moments.append([CNOT(qubits[15], qubits[79])])
    moments.append([CNOT(qubits[14], qubits[78])])
    moments.append([CNOT(qubits[13], qubits[77])])
    moments.append([CNOT(qubits[12], qubits[76])])
    moments.append([CNOT(qubits[11], qubits[75])])
    moments.append([CNOT(qubits[10], qubits[74])])
    moments.append([CNOT(qubits[9], qubits[73])])
    moments.append([CNOT(qubits[8], qubits[72])])
    moments.append([CNOT(qubits[7], qubits[71])])
    moments.append([CNOT(qubits[6], qubits[70])])
    moments.append([CNOT(qubits[5], qubits[69])])
    moments.append([CNOT(qubits[4], qubits[68])])
    moments.append([CNOT(qubits[3], qubits[67])])
    moments.append([CNOT(qubits[2], qubits[66])])
    moments.append([CNOT(qubits[1], qubits[65])])

    circuit = cirq.Circuit()

    # cirq will flush gates left, the strategy argument given will
    #prevent this. If this is not desired remove the strategy argument.
    for moment in moments:
        circuit.append(moment, strategy=cirq.circuits.InsertStrategy.NEW_THEN_INLINE)

    return circuit

    # # Convert moments to a circuit and return it
    # return cirq.Circuit(moments)

if __name__ == '__main__':
    ''' This bit will only run if this file is executed.
    This allows you to import the function to other files ignoring
    whatever is below. This part isn't needed for the gui '''

    import cirq

    circuit = build_circuit()
    print(circuit)
